### ISSUE TITLE
Topic payload is inconsistent

### ISSUE THREAD

**Issue by darya-mart** [PlanQK/platform#86] opened 2023-08-08 15:48 UTC
**Current Behavior**
Topic payload contains inconsistent (compared to frontend) information about entities. 

**Steps to Reproduce**
1. Go to https://platform.planqk.de/algorithms/1acb3412-d347-4a2c-8dcc-24bd7568ce9f/ 
2. Click the checkbox next to "NISQ" (so it is checked)
3. See the field `"nisqReady": false ` in the topic payload
4.  Uncheck the field "NISQ"
5.  See the field `"nisqReady": true` in the topic payload

The same "delayed" behavior appears on any modification, regardless of the field being modified.

**Expected Behavior**
Topic payload contains the same information as displayed in the frontend / stored in the database.

**Comment by miwurster** [comment] 2023-09-04 11:10
Hi @mdafokus, I've taken a look into this and after investigating this I found out that it was due to the "service event" change lately. I had to kinda revert this change which means currently we do not send "service events" any longer. However, the payload for Algorithm, Implementation, Data Pool, and Use Case should be consistent again. Please have a look and let me know. 

We can leave this issue open until I find a solution for the "service events" ... but we could also create a new issue. whatever you like more :-)

**Comment by radufalcusanStoneone** [comment] 2023-10-04 08:10
I am closing this issue as we have released the "Service Events" feature and the rest of the events should be consistent. @mdafokus Please feel free to let us know if you notice any unintended behaviour. :)

**Closed as completed by radufalcusanStoneone** 2023-10-04 08:10 UTC
Labels: bug, in progress
